### ISSUE TITLE
Simulations aborted on Mac

### ISSUE THREAD

**Issue by axiezai** [jonescompneurolab/hnn#11]
Hello, 

I just did a fresh install of HNN on a macOS High Sierra. 

When I tried to run the Simulating Rhythmic Proximal Inputs: Alpha Only tutorial, the simulation instantly aborts and the terminal gives off the following message: 

Starting simulation. . .
--------------------------------------------------------------------------
mpiexec noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
WARN: could not read simulation outputs: dict_values(['/Users/ashish/hnn/data/default/dpl.txt', '/Users/ashish/hnn/data/default/rawspec.npz', '/Users/ashish/hnn/data/default/spk.txt', '/Users/ashish/hnn/data/default/param.txt'])

Not really informative as the error message doesn't know what exactly caused the simulation to abort. Please let me know if you need any other info to solve this. Thank you!

**Comment by samnemo** [comment]
Robert - any suggestions?

**Comment by ramcdougal** [comment]
Do any of the tutorials work?

If not, does NEURON load successfully?

e.g. if you do

    cd ~/hnn
    python

and then in python try "import neuron", does it succeed or fail?

If it fails, try:

    cd ~/hnn
    rm -fr x86_64
    nrnivmodl mod/

and then see if the previous test now succeeds or fails.

**Comment by ramcdougal** [comment]
One other thing to check:

Does typing "python" load Python 2 or Python 3? (It should say in the banner.)

**Comment by axiezai** [comment]
After some digging, it seems that the newer versions of MacOS doesn't include openMPI, which is required to run HNN simulations I assume? After installing I am now seeing the following:

Starting simulation. . .
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[iMac-Pro.radiology.ucsf.edu:44424] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[iMac-Pro.radiology.ucsf.edu:44424] OPAL ERROR: Not initialized in file pmix2x_client.c at line 109
[iMac-Pro.radiology.ucsf.edu:44425] OPAL ERROR: Not initialized in file pmix2x_client.c at line 109

 does this help?

**Comment by axiezai** [comment]
hi @ramcdougal 
"import neuron" works
>>Python version is 3.6.5

**Comment by ramcdougal** [comment]
Just to confirm: Are you using Anaconda Python?

I would have expected doing the conda install of mpi4py to install openmpi, but you can try removing the openmpi you installed and explicitly doing the conda install of openmpi:

    sudo conda install -c mpi4py openmpi 

(sudo is assuming you've installed for all users; if it's a local install, do not use "sudo").

**Comment by axiezai** [comment]
I did the conda install for mpi4py and openmpi, loaded the tutorial parameters, clicked run simulation and now i'm getting the following:

Starting simulation. . .

[iMac-Pro.radiology.ucsf.edu:46680] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122
[iMac-Pro.radiology.ucsf.edu:46680] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46683] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122

[iMac-Pro.radiology.ucsf.edu:46683] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122
[iMac-Pro.radiology.ucsf.edu:46683] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46684] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122
[iMac-Pro.radiology.ucsf.edu:46684] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46685] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122

[iMac-Pro.radiology.ucsf.edu:46685] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122
[iMac-Pro.radiology.ucsf.edu:46685] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46688] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122

[iMac-Pro.radiology.ucsf.edu:46688] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122
[iMac-Pro.radiology.ucsf.edu:46688] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46689] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122
[iMac-Pro.radiology.ucsf.edu:46689] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46690] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122

[iMac-Pro.radiology.ucsf.edu:46690] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122
[iMac-Pro.radiology.ucsf.edu:46690] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46691] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122

[iMac-Pro.radiology.ucsf.edu:46691] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122
[iMac-Pro.radiology.ucsf.edu:46691] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46692] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122
[iMac-Pro.radiology.ucsf.edu:46692] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46681] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46682] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46686] PMIX ERROR: UNPACK-PAST-END in file unpack.c at line 122
[iMac-Pro.radiology.ucsf.edu:46686] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46687] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46693] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46694] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46695] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46684] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46686] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46688] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46687] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
[iMac-Pro.radiology.ucsf.edu:46691] PMIX ERROR: SUCCESS in file event/pmix_event_registration.c at line 91
WARN: could not read simulation outputs: dict_values(['/Users/ashish/hnn/data/OnlyRhythmicProx/dpl.txt', '/Users/ashish/hnn/data/OnlyRhythmicProx/rawspec.npz', '/Users/ashish/hnn/data/OnlyRhythmicProx/spk.txt', '/Users/ashish/hnn/data/OnlyRhythmicProx/param.txt'])

**Comment by nrnhines** [comment]
To help diagnose. results of the following tests may be useful. Run tests in a terminal.

1) Does mpi work?
`
$ mpiexec -n 2 echo "hello"
hello
hello
`

2) does nrniv work without mpi and python
`
nrniv -nobanner -nopython -c '{print "hello" quit()}'
hello
`

3) do nrniv and mpi work together but without python
`
$ mpiexec -n 2 nrniv -nobanner -nopython -mpi -c '{print "hello" quit()}'
numprocs=2
hello
hello
`

4) can you launch nrniv and use python
`
$ nrniv -nobanner -python -c 'from neuron import h; print("Hello"); h.quit()'
Hello
`
5) do all three work when launching nrniv
`
$ mpiexec -n 2 nrniv -nobanner -mpi -python  -c 'from neuron import h; pc = h.ParallelContext(); print ("I am %d of %d" % (int(pc.id()), int(pc.nhost()))); h.quit()'
numprocs=2
I am 0 of 2
I am 1 of 2
`

**Comment by blakecaldwell** [comment]
@vogdb thanks for the instructions above.

This error can come about in at least a couple of ways. Even if `LD_LIBRARY_PATH` is set to where `libmpi.dylib` exists, the error may not be resolved if `libmpi.10.dylib` does not exist. I needed to create a link:
```
cd $CONDA_PREFIX/lib
ln -s libmpi.1.dylib libmpi.10.dylib
```

I don't know where the 10 comes from. Perhaps @ramcdougal has some insight from the NEURON macOS installer?

**Comment by axiezai** [comment]
I'm glad @vogdb and @blakecaldwell provided some easy solutions! 

To be honest, I don't have access to the Mac machine I did this install on anymore, it wasn't my Mac :(

So I can't provide more info on my end, apologies. If we can confirm thatextra 10 in `libmpi.10.dylib` isn't an issue, perhaps we can close this? 

Thanks again for all the help and debugging! Really grateful :)
