### ISSUE TITLE
Spike viewer doesn't load for a resting network simulation

### ISSUE THREAD

**Issue by stephanie-r-jones** [jonescompneurolab/hnn#112]
In a simulation with no driving inputs (e.g. no evoked inputs or rhythms inputs), the network goes to rest and the somatic voltages can be viewed as such. However, the spike viewer wouldn't open to display no spiking activity. Perhaps this is because there is also no driving input, and driving input is needed to initiate the spike viewer?

**Comment by blakecaldwell** [comment]
Thanks @stephanie-r-jones for opening the issue. This was an easy fix. Merging into master now
