### ISSUE TITLE
Optimization crashes when input times > data

### ISSUE THREAD

**Issue by kohl-carmen** [jonescompneurolab/hnn#116]
I think I broke the optimization because I have an input into the network that is set to a time greater than the length of my data (I only entered 80ms of data and had a distal input with an initial timing of 99ms). That's clearly my own fault, but maybe there's a way to not let users be as silly as me?

Loaded data in  C:\Users\ckohl\Documents\SourcePlay\adult_r_base_80ms.txt
Starting simulation (6 cores). . .
Starting model optimization. . .
Optimization step 1, iteration 1
weighted RMSE = 0.031590, RMSE = 0.032852
...
Optimization step 1, iteration 30
weighted RMSE = 0.032096, RMSE = 0.033743
Traceback (most recent call last):
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 208, in run
    self.optmodel() # run optimization
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 411, in optmodel
    self.runOptStep()
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 557, in runOptStep
    opt_results = optimize(self.opt_params['ranges'], self.opt_params['num_sims'], algorithm)
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 546, in optimize
    opt_results = opt.optimize(opt_params)
  File "C:\Users\ckohl\Miniconda3\envs\hnn\lib\site-packages\nlopt\nlopt.py", line 402, in optimize
    return _nlopt.opt_optimize(self, *args)
ValueError: bounds 0 fail 74.4327 <= 99.6567 <= 80

**Comment by blakecaldwell** [comment]
Thank you @kohl-carmen! I’ll make sure this check is part of the upcoming optimization improvement.

**Comment by blakecaldwell** [comment]
Note that commit b81c148 also fixes a serious typo in calculating weights for using RMSE in optimization
