### ISSUE TITLE
Optimization fails after step 1

### ISSUE THREAD

**Issue by kohl-carmen** [jonescompneurolab/hnn#118]
C:\Users\ckohl\hnn>python hnn.py
Loaded data in  C:\Users\ckohl\Documents\SourcePlay\adult_r_base.txt
Starting simulation (6 cores). . .
Starting model optimization. . .
Optimization step 1, iteration 1
weighted RMSE = 0.034794, RMSE = 0.036376
...
Optimization step 1, iteration 30
weighted RMSE = 0.042405, RMSE = 0.041158
Optimization step 2, iteration 1
Traceback (most recent call last):
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 2452, in updatesaveparams
    for win in self.lsubwin: win.setfromdin(dtest)
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 1832, in setfromdin
    self.updateDispRanges()
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 1763, in updateDispRanges
    initial_value = float(self.initial_opt_info[tab_index][label]['initial'])
KeyError: 't_evdist_1'

**Comment by blakecaldwell** [comment]
Fixed in commit b882b39 from range slider merge
