### ISSUE TITLE
add a link to hnn-core

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn#147]
It would be nice if a link to hnn-core can be added on the website saying there is a WIP command-line API that is being developed here: https://hnnsolver.github.io/hnn-core/. So, those with more programming experience can give it a try if they want to try more advanced things.

**Comment by blakecaldwell** [comment]
I can put a link on the readme this github project. Since it is a WIP, I'm not sure about mentioning it on the hnn.brown.edu web page. Could you start a discussion via email? Thanks.

**Comment by jasmainak** [comment]
sent email and happy if only a link can be added to the readme.
