### ISSUE TITLE
Crashed loading file

### ISSUE THREAD

**Issue by kohl-carmen** [jonescompneurolab/hnn#154]
making dout: C:\Users\ckohl\hnn_out\data\default
making dout: C:\Users\ckohl\hnn_out\data\default
making dout: C:\Users\ckohl\hnn_out\data\from_here_10_opt_adjusted
Traceback (most recent call last):
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 3248, in selParamFileDialog
    self.baseparamwin.updateDispParam()
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 2971, in updateDispParam
    for dlg in self.lsubwin: dlg.setfromdin(din) # update to values from file
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 2492, in setfromdin
    self.updateOptDialog()
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 2429, in updateOptDialog
    self.rebuildOptStepInfo()
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 2170, in rebuildOptStepInfo
    self.ltabkeys.pop(tab_index)
IndexError: pop index out of range

**Comment by blakecaldwell** [comment]
Hi @kohl-carmen I'm having trouble reproducing this. Would you mind sending me from_here_10_opt_adjusted.param if that's what you loaded before this crash? Thanks!

**Comment by blakecaldwell** [comment]
Okay, I wonder if this is from an older version (a couple weeks ago). Would you mind sending me the output of the following:
```
git show -s --oneline
```

Also, I just pushed an update that will gracefully handle all exceptions, including those when non-data or non-param files are loaded. To update to the new version: 
```
git checkout master
git pull origin master
```

**Comment by kohl-carmen** [comment]
You're right, I hadn't updated hnn. It works fine now!
