### ISSUE TITLE
[Feature Request]: Allow for different bin widths of each input time histogram

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn#17]
For each histogram plot showing the distribution of model input times, the bin width should be dynamically set based on the start time stdev parameter so that the bin width is not too large or too small.

**Comment by blakecaldwell** [comment]
Ryan, it would be great to start with your WIP code

**Comment by blakecaldwell** [comment]
This was completed in #82 Thanks @rythorpe
