### ISSUE TITLE
HNN-Netpyne: Missing analysis plotting functions (iplotDipolePSD, iplotDipoleSpectrogram) 

### ISSUE THREAD

**Issue by mkhalil8** [jonescompneurolab/hnn#171]
I get an error when running createSimulateAnalyze(), I could not find the following functions in Netpyne:

cfg.analysis['iplotDipolePSD'] = {'showFig': True, 'maxFreq': 80}  # change freq to 40 for alpha&beta tut

cfg.analysis['iplotDipoleSpectrogram'] = {'showFig': True, 'maxFreq': 80} # change freq to 40 for alpha&beta tut

**Comment by blakecaldwell** [comment]
@mkhalil8 thanks for creating this issue. Can you check that your version of netpyne (collected via pip perhaps?) is at least 0.9.4? If not, you may need to clone the netpyne repository and build the module via `python setup.py install`.

This is the commit that is important to get for 
https://github.com/Neurosim-lab/netpyne/commit/47a4a2442b9d90873692dda505d4a22e1d920610

**Comment by mkhalil8** [comment]
Many Thanks blakecaldwell, Your answer has resolved the problem.
 
I am yet facing another issue, I cannot plot rasters at all, the error is:
KeyError: 'gid'
> /anaconda3/lib/python3.6/site-packages/netpyne/analysis/spikes.py(379)plotRaster()
-> df = df.sort_values(by='gid')
There was an exception in plotRaster():

Can you please help me with that.

**Comment by blakecaldwell** [comment]
@mkhalil8 good to hear that some progress was made. Happy to look at this issue... Could you provide the commands you ran to get to this point? I notice that when I run python init.py in the netpyne subdirectory, the output includes a different error about raster plots
```
Plotting interactive raster ...
There was an exception in iplotRaster(): 
 'NoneType' object has no attribute 'copy' 
(<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'copy'"), <traceback object at 0x12f41f960>)
```

**Comment by mkhalil8** [comment]
Thanks again Blake, Yes I run python init.py in netpyne directory, and it gives me the following error:

There was an exception in iplotRaster(): 
 'gid' 
(<class 'KeyError'>, KeyError('gid',), <traceback object at 0x1333b24c8>)

I tried:  nrniv -python tut1.py , but it gave me the following error:

There was an exception in plotRaster(): 
  
(<class 'bdb.BdbQuit'>, BdbQuit(), <traceback object at 0x11e36e2c8>)

**Comment by blakecaldwell** [comment]
Thanks @mkhalil8. I'm not yet able to reproduce the same error. You said tut1.py is also giving an error in plotRaster(), but I just ran it successfully. We can start by checking that netpyne is working correctly.  Can you confirm your version of netpyne and NEURON? Also what OS are you using?
```
(mne) MacBook-Pro:Downloads blake$ python
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netpyne
>>> netpyne.__file__
'/Users/blake/miniconda3/envs/mne/lib/python3.7/site-packages/netpyne/__init__.py'
>>> netpyne.__version__
'0.9.4'
>>> 
(mne) MacBook-Pro:Downloads blake$ nrniv version
NEURON -- VERSION 7.7.2 7.7 (2b7985ba) 2019-06-20
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2018

0 nrniv: can't open version
```

**Comment by mkhalil8** [comment]
I am using Macbook like you, this is my python, netpyne, neuron version:

apples-MacBook-Pro-3:Netpyne_tutorials mostafa$ python
Python 3.6.7 |Anaconda custom (64-bit)| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netpyne
>>> netpyne.__version__
'0.9.4'
>>> import neuron
NEURON -- VERSION 7.5 master (643b6f9) 2018-04-27
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2016
See http://neuron.yale.edu/neuron/credits

**Comment by blakecaldwell** [comment]
@mkhalil8 I tried duplicating your environment but ran into troubles installing neuron 7.5. You might want to upgrade to a more recent version. I also think we should confirm with @salvadord that 0.9.4 is the correct version of netpyne to use with HNN. The error about `KeyError('gid',)` indicates 'gid' is missing from an internal structure. 
https://github.com/Neurosim-lab/netpyne/blob/v0.9.4/netpyne/analysis/spikes.py#L377

@salvadord Does this error mean anything to you?

**Comment by mkhalil8** [comment]
Hi Blake, sorry for my late replies, I am an MD and doing shifts and busy rotation till February :)

I upgraded neuron to 7.7.2 but still got the same error, I guess I shall try using another NetPyne version.

**Comment by mkhalil8** [comment]
Hi Blake, I upgraded Neuron to 7.7.2 then upgraded netpyne using pip (although I had netpyne 0.9.4 but it has upgraded some packages also), and it worked :)

**Comment by mkhalil8** [comment]
Hi Blake, Can you please help me with another bug, When I plot any results of Netpyne-HNN at Bokeh it plots the results in the same Safari window consecutively, (for example the raster then PSD then Dipole) and I wouldnot be able to see them one by one.

Another issue is that on terminal it send the following error (although it plots), I assume it is a problem in converting network parameters data from HNN param file to Netpyne cfg file:

Plotting interactive spike histogram...
[Figure(id='3d7c030a-b9a4-471f-bea7-4cd5ace73fd1', ...)]
/anaconda3/lib/python3.6/site-packages/bokeh/models/sources.py:137: BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('x', 6800), ('y', 6801)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.items())), BokehUserWarning))
/anaconda3/lib/python3.6/site-packages/bokeh/models/sources.py:137: BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('x', 6800), ('y', 6801)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.items())), BokehUserWarning))
/anaconda3/lib/python3.6/site-packages/bokeh/models/sources.py:137: BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('x', 6800), ('y', 6801)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.items())), BokehUserWarning))

**Comment by salvadord** [comment]
@mkhalil8 thanks for your feedback!

Blake, I totally agree with your suggestions.

Two other things that came to mind:
1) you can call plots from the terminal interactively after the simulation has finished: e.g. sim.analysis.iplotRaster()
2) Maybe try setting a different default browser (eg Chrome) to see if that opens new tabs for each plot.

I'll let you know if we can think of anything else.

**Comment by mkhalil8** [comment]
@blakecaldwell @salvadord , Thank you for your reply and suggestions.
For the plotting problem on HNN-Nepyne, I have changed the default browser from safari to chrome and it worked perfectly :) (each figure is plotted on a separate tab) 👍 
I can plot successfully anything on Netpyne alone with no problems. My understanding is that HNN-Netpyne uses iplot function and Bokeh (which depends on the default browser, in my case it was Safari). While Netpyne alone uses Matplotlib which directly plots figures without browser.

For the second issue (the Bokeh error message), It is not causing any problems but just throws the error : ColumnDataSource's columns must be of the same length. Current lengths: ('x', 6800), ('y', 6801) .
Right now I am able to plot successfully, will see if that will cause problems in the future.
Thanks a lot for your help @blakecaldwell @salvadord

**Comment by blakecaldwell** [comment]
I'm going to close this for now. @mkhalil8 please let us know if you have any new issues.
