### ISSUE TITLE
Deleting an evoked input among a series of evoked inputs causes improper ordering/labeling in param file

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn#20]
I originally had 4 evoked proximal inputs and then deleted the 2nd input through the GUI. This caused a problem in how the simulation recognized my specified inputs in the param file. Proximal input 3 was implemented in the simulation but didn't show up properly in the main dipole plot (via a red arrow), and proximal input 4 wasn't implemented at all. See the attached param file for reference.

[param_file.zip](https://github.com/jonescompneurolab/hnn/files/2583438/param_file.zip)

**Comment by samnemo** [comment]
Can you also provide the param file with the 4 evoked inputs that works properly?

**Comment by rythorpe** [comment]
Attached is a .zip file with both files - before and after deletion of the 2nd prox. input.

[param_file.zip](https://github.com/jonescompneurolab/hnn/files/2585606/param_file.zip)

**Comment by samnemo** [comment]
fixed issue with removing middle proximal/distal evoked inputs by downshifting later evoked inputs
