### ISSUE TITLE
Replicate periodic evoked inputs with rhythmic inputs

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn#208]
I currently have a param file with evoked inputs that have periodic spacing. My goal is to replicate the simulation with only rhythmic inputs, however, there seems to be a discrepancy in how synaptic weights are assigned for evoked vs. rhythmic inputs. The following screenshots demonstrate this issue and their corresponding param files are attached. Note that, according to the param files, the synaptic conductancies for proximal and distal inputs are congruent across simulations.
![Screenshot from 2020-04-30 20-36-46](https://user-images.githubusercontent.com/20212206/80773238-4e306000-8b27-11ea-9c4f-23b3a3c86120.png)
![Screenshot from 2020-04-30 20-29-04](https://user-images.githubusercontent.com/20212206/80773310-8a63c080-8b27-11ea-86bb-35b287b70346.png)

I realize that there is a difference in how jitter is applied to individual evoked inputs vs. a series of rhythmic inputs; however, the fact that the simulations above produce dipoles that are different by an order of magnitude is confusing.

[param_files.zip](https://github.com/jonescompneurolab/hnn/files/4562140/param_files.zip)

**Comment by blakecaldwell** [comment]
I just observed this too with the default parameter set as a starting point where rhythmic inputs appear to have more of an effect. The code for generating inputs could use a lot of improvement. There aren't any methods for inspecting the generated rhythmic feeds in feed.py right now. If you wanted to add a method that allows comparison at the python level, we could definitely reuse that code as a test once integrated with hnn core.
<img width="1381" alt="Screen Shot 2020-05-01 at 2 38 54 PM" src="https://user-images.githubusercontent.com/2258507/80832659-11ae4400-8bbb-11ea-8b66-ab60c135c707.png">
<img width="1312" alt="Screen Shot 2020-05-01 at 2 39 35 PM" src="https://user-images.githubusercontent.com/2258507/80832677-1a067f00-8bbb-11ea-8468-2aa0ca005b5b.png">

**Comment by stephanie-r-jones** [comment]
One important difference in the evoked vs rhythmic input is the spatial spread of the input in the network. If I recall correctly, the evoked input targets the center of the network with a gaussian falloff, while the rhythmic input has a wider fall off and contacts all of the cells with nearly equal strength.  There is also the issue of synchrony of the inputs, and evoked inputs have the option of being synchronous or asynchronous to the cells, while this is not an option for rhythmic inputs. We need to clarify this on the website.

**Comment by rythorpe** [comment]
I thought the gaussian falloff was for local network connection weights 
but that synchronous evoked inputs targeted all relevant cells 
(according to their type) at the same time and same strength. Is that 
not correct?

**Comment by blakecaldwell** [comment]
@rythorpe I believe you are the best person to say what work remains to be done with this or if it will be part of hnn-core. Could you update this issue?

**Comment by rythorpe** [comment]
@blakecaldwell I think it will be much more intuitive to address this issue in hnn-core. Most of it can be addressed as we update the API.

**Comment by blakecaldwell** [comment]
Closed in favor of https://github.com/jonescompneurolab/hnn-core/issues/114
