### ISSUE TITLE
HNN Installation Issue

### ISSUE THREAD

**Issue by aba407** [jonescompneurolab/hnn#210]
I was able to download Download Docker and the HNN repo, but when I run `./hnn_docker.sh -u start` in Terminal during the initial installation process, I get an error message saying that:
`Error: set_local_display_from_port (L:1613) expects DISPLAY to be set`
`Error: Script cannot continue`
![Terminal Error](https://user-images.githubusercontent.com/64662949/80838713-a5860d00-8bc7-11ea-83d0-e740f734294c.jpg)

**Comment by blakecaldwell** [comment]
@aba407 Thanks for posting this. It looks like a problem with our script, but it should be a quick fix. Would you mind attaching the `hnn_docker.log` file (it should be in the same `hnn` directory)?

**Comment by aba407** [comment]
[hnn_docker.log](https://github.com/jonescompneurolab/hnn/files/4566194/hnn_docker.log)

**Comment by aba407** [comment]
@blakecaldwell  
 [hnn_docker.log](https://github.com/jonescompneurolab/hnn/files/4566518/hnn_docker.log)
> @aba407 Thanks for posting this. It looks like a problem with our script, but it should be a quick fix. Would you mind attaching the `hnn_docker.log` file (it should be in the same `hnn` directory)?

**Comment by blakecaldwell** [comment]
Hi @aba407 I think that if you check out the latest version with `git pull origin master` this bug will be fixed. Thanks!

**Comment by blakecaldwell** [comment]
@aba407 I believe this was fixed. Closing issue.
