### ISSUE TITLE
Configure optimization not allowed in native Ubuntu installation 

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn#215]
I've established a native HNN installation on Ubuntu that seems to run simulations just fine. When I load the gui, however, Simulation->Configure Optimization is grayed out and appears to be inaccessible. At first I wondered if there was an issue with importing the nlopt module, but it loads just fine within my conda environment. Any ideas?

**Comment by blakecaldwell** [comment]
Just checking, you have loaded a data file, right?

**Comment by rythorpe** [comment]
Yes, it is the default.param file.

**Comment by blakecaldwell** [comment]
What data file are you comparing RMSE to?

**Comment by rythorpe** [comment]
Oh boy. That's what I was doing wrong :laughing:

**Comment by rythorpe** [comment]
Everything works just fine - thanks @blakecaldwell!
