### ISSUE TITLE
How to convert EEG to Source Localized Data

### ISSUE THREAD

**Issue by INNFINITEMINDS** [jonescompneurolab/hnn#219]
Help Needed !

I wanted EEG recordings to be transformed into source-localized data.(primary current dipoles.)
Also How can i save it(source-localized data) in a text file with one column indicating time points and a second column containing amplitude data. These are in the unit of nAm.
As i found that these software package do such task, these are MNE-Python or the MATLAB toolbox FieldTrip.
But i am new to this,i don’t know proper steps /which scripts /code to use in order to convert eeg recordings to source localized data.
So please someone help me how to complete this . Which code/scripts i have to use from above mentioned software’s(MNE-python/FieldTrip) .
![image](https://user-images.githubusercontent.com/28722237/88748719-5708f000-d16f-11ea-8a08-c9675b058fa3.png)
Needed Guidance.

Thanks,
Arpit

**Comment by jasmainak** [comment]
This partly answers your question: https://jonescompneurolab.github.io/hnn-core/auto_examples/plot_simulate_somato.html#sphx-glr-auto-examples-plot-simulate-somato-py

If you always stay in `hnn-core` you don't ever need to save to a text file. Unfortunately, the interface is not very user friendly yet. But otherwise, you should write the `stc.data` and `stc.times` using numpy functions such `np.savetxt`. Give it a try and let us know if you get stuck.

**Comment by INNFINITEMINDS** [comment]
> This partly answers your question: https://jonescompneurolab.github.io/hnn-core/auto_examples/plot_simulate_somato.html#sphx-glr-auto-examples-plot-simulate-somato-py
> 
> If you always stay in `hnn-core` you don't ever need to save to a text file. Unfortunately, the interface is not very user friendly yet. But otherwise, you should write the `stc.data` and `stc.times` using numpy functions such as `np.savetxt`. Give it a try and let us know if you get stuck.

Respected Sir,

Thanks for replying.
i have just gone through the link that you had provided.
I have following questions: (as i am new to this )

the above link that u had provided in this they are using   somato dataset which is given by mne dataset.  
so my question is I have recorded my own EEG data ,than how should i proceed /what steps should i have to do in order to  convert it into source localized data.
Also i have gone through this link : [https://mne.tools/dev/auto_tutorials/intro/plot_10_overview.html#sphx-glr-auto-tutorials-intro-plot-10-overview-py]

in this they have MEG sensor data . But i don't have this MEG sensor data while i recording  EEG signal.

so how should i proceed/steps/ procedure from **Raw EEG data of my head to   source-localized data**.and then u**se this data In HNN**

still i am confused and i don't have clear picture in my mind what should i do ?

please clarify my doubts. Also Guide me .

Awaiting for your response  .(Sorry for asking such questions)

Thanks,
Arpit

**Comment by INNFINITEMINDS** [comment]
Also sir i have just gone through your thesis https://jasmainak.github.io/ .
In this  chapter 4  4.1 -4.4  of your phd thesis
should i have  to all the above mentioned steps  and apply to my own EEG recordings ?so that to  covert Raw EEG data of my head to source-localized data.and then use this data In HNN?
Thanks,
Arpit

**Comment by jasmainak** [comment]
Yes, chapters 4.4.1 - 4.4 describe the best practices but you can also read the associated publication. For EEG the steps are almost the same but you'll need to use a template MRI if you don't have an MRI scan for the subject. See this tutorial: https://mne.tools/stable/auto_tutorials/source-modeling/plot_eeg_no_mri.html. And yep you're right, that you have to first source localize and then use that data for interpretation in HNN.

**Comment by INNFINITEMINDS** [comment]
> Yes, chapters 4.4.1 - 4.4 describe the best practices but you can also read the associated publication. For EEG the steps are almost the same but you'll need to use a template MRI if you don't have an MRI scan for the subject. See this tutorial: https://mne.tools/stable/auto_tutorials/source-modeling/plot_eeg_no_mri.html. And yep you're right, that you have to first source localize and then use that data for interpretation in HNN.

ok sir ,
as u have said i have to  first source localize and then use that data for interpretation in HNN.
But still sir  i have no clear picture in my mind what steps i have to do for the eeg to source localisation along with MRI template,I am confused.
sir its my request to explain the steps/procedure todo that or some links.so that i can refer them and do my work.
I am new to this ,i am confused .what steps i had to follow.
awaiting for your reply .Also i am excited to do this work.
thanks,
arpit

**Comment by blakecaldwell** [comment]
@INNFINITEMINDS the MNE tutorials that @jasmainak linked to are probably the best resources for source-localizing EEG data.

Once you have completed source localization, you can create a .txt file from your data arrays using code similar to this:
https://github.com/jonescompneurolab/hnn-core/blob/master/hnn_core/dipole.py#L219-L221
