### ISSUE TITLE
Trouble installing HNN on Windows 10 using Docker

### ISSUE THREAD

**Issue by eblundon** [jonescompneurolab/hnn#228]
I'm having trouble installing HNN on Windows 10. I've got to the "./hnn_docker.sh -u start" part of the install, but no HNN GUI pops up. My issue also doesn't seem to be on the troubleshoot page. The docker output is below. Any idea what might be the matter? I also tried to post the log file but the hnn_docker.log command didn't work.

![image](https://user-images.githubusercontent.com/71042208/92653052-c9670700-f2bb-11ea-9585-7a84cee2d07e.png)

L

**Comment by blakecaldwell** [comment]
@eblundon Thanks for creating this issue. I'm hopefull that the log file will give me some clues. The `hnn_docker.log` file is just a regular file in your home directory, `~/hnn/hnn_docker.log`. You can just use File Explorer to drag and drop `hnn_docker.log` into a comment here.

@INNFINITEMINDS this may be the same issue you are running into #163

**Comment by eblundon** [comment]
Oh sorry about that, I misunderstood. I don't have a .log file, but I have a .txt file that looks like it could be a log file. Hope this is what you're looking for.
[hnn_docker.log](https://github.com/jonescompneurolab/hnn/files/5198029/hnn_docker.log)

**Comment by blakecaldwell** [comment]
@eblundon could you try this code update to see if the problem resolves?  The error message in `hnn_docker.log` is related to VcXsrv not being reachable.  I've tried the IP address 127.0.0.1 instead of `localhost`, but I'm not positive that will fix it.

```
git fetch origin pull/218/head:issue_217_fix
git checkout issue_217_fix
./hnn_docker.sh start
```

Once this issue is fixed (it will get closed), you can switch back to the updated master branch with:
```
git checkout master
git pull origin master
./hnn_docker.sh start
```

**Comment by ShiriMakov** [comment]
Following up on #186 here:

After pulling from master, post this merge, I am still having issues.
Once again `Checking for X11 authentication keys` failed.
Here are the logs:
[hnn_docker.log](https://github.com/jonescompneurolab/hnn/files/5313657/hnn_docker.log)

**Comment by blakecaldwell** [comment]
@ShiriMakov I think I found the issue... the instructions pointed to an old version of VcXsrv. Upgrading to a newer version fixes this problem. I have used 1.20.60. and 1.20.8.1 successfully. Hopefully, that does it. Sorry for overlooking this! I'll be following up with a fix to instructions very soon.

https://sourceforge.net/projects/vcxsrv/

**Comment by blakecaldwell** [comment]
I wanted to make sure other users don't keep getting the wrong version. Feel free to reply to this issue if the xauth errors persist. Thanks for reporting it to us!
