### ISSUE TITLE
Docker Toolbox on Win 10 Home fails: Checking that xauth key in container matches... failed

### ISSUE THREAD

**Issue by carolinafernandezp** [jonescompneurolab/hnn#233]
Hello,

I am installing HNN on Windows 10 (Home). It seems like I am unable to Start HNN for the following reason:

![image](https://user-images.githubusercontent.com/51917715/93388562-e5792400-f838-11ea-9066-22dac09a328f.png)

Please find my .log file attached.

[hnn_docker.log](https://github.com/jonescompneurolab/hnn/files/5234742/hnn_docker.log)

I would appreciate your help with this!

Thanks,
Carolina

**Comment by blakecaldwell** [comment]
Hi, could you please see if the code from this issue fixes the problem?
https://github.com/jonescompneurolab/hnn/issues/217

We are going to provide a new installation method for Windows Home using WSL that can replace docker. Please let me know if you are still running into problems and I can continue to track down a temporary fix.

**Comment by blakecaldwell** [comment]
The changes from #217 and another one specific to Windows 10 Home are now part of the master branch.

After changing to the installation directory:
```
git pull origin master
./hnn_docker.sh -u start
```

**Comment by blakecaldwell** [comment]
@carolinafernandezp could you please confirm if this is fixed or there are still errors? Thanks.
