### ISSUE TITLE
Update HNN installation instructions

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn#240]
Several changes to the documentation for installing HNN GUI

- [x] Use `pip install neuron` instead of NEURON installers
- [x] Remove "native" from install procedure names, instead call "Python" install procedure (will eventually use `pip` for HNN)
- [x] Create a Python install page for Linux
- [x] Change the preferred installation methods:
   - Windows: WSL (#238) instead of Docker.
   - Mac: Python
   - Linux: Python
- [x] Mark Docker and Powershell installation instructions deprecated

**Comment by ntolley** [comment]
Quick fix related to this issue. The [ubuntu native install ](https://github.com/jonescompneurolab/hnn/blob/master/installer/ubuntu/native_install.md)instructions reference `installer.sh`, which doesn't match the actual file included `hnn-ubuntu.sh`. Figured this would be a good spot if you're already working on a PR to close this issue.
