### ISSUE TITLE
improve installation process

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn#25]
@samnemo I started trying to play around with hnn but I hit a roadblock.

It seems that the [installation process](https://github.com/jonescompneurolab/hnn/blob/master/installer/ubuntu/installer.sh) requires one to have sudo rights. This is a no go for many people working in labs since they do not necessarily have sudo rights. Typically, in the python world, we use the anaconda package which is added to the path. Then everything else can be done without sudo.

Are there any libraries that _really_ need sudo? Otherwise, I would recommend, replacing this with non-sudo options. I'm going to attempt an install without sudo, so I can make a pull request for this if you agree.

Also, it would be good to have some developer documentation -- such as a `CONTRIBUTING.md` (that github recommends) so those wanting to edit the code can understand how to get into it! Happy to help with it

**Comment by bloyl** [comment]
Interestingly I just spent today doing exactly that.

Attached is the install script i ended up using. There are a few stray
/usr/local s in the hnn src i can put up a PR tomorrow if its desired.

-Luke

**Comment by jasmainak** [comment]
Wow, that would be great! I don't see the attached script. Could you share it via a gist or something? Thanks!

**Comment by bloyl** [comment]
Mainak,
I'm on my phone so hopefully this link will do for now.

Note this doesn't deal with the system dependencies. Only the Python and things that need building.

https://drive.google.com/file/d/0B4FnwYbkdwdlWnk2MVNoT0lzeWNGNWNSREhVMGFiOW5JNmtv/view?usp=drivesdk

**Comment by jasmainak** [comment]
Power of open science :) Thanks Luke! So far I am making good progress, and I managed to install nrn and iv but I had to make two modifications:

1. Add `$ export PATH="$PATH:/usr/lib64/mpich/bin/"` for installing mpi4py using pip
2. `$ conda install libtool=2.4.2` for installing iv. I had 2.4.6 and it didn't like it

**Comment by samnemo** [comment]
@ramcdougal - may want to take note of what Mainak & Luke are working on

**Comment by blakecaldwell** [comment]
Closing this with our completion of new Docker-based installation instructions on the HNN website:
https://hnn.brown.edu/index.php/installation-instructions/

The original points raised about sudo rights during installation is addressed in two ways:
1. If Docker is installed and usable by non-root users, any user can instantiate the HNN container without sudo.
2. In the Dockerfile the installation is done as "hnn_user". If someone wishes to reproduce this on an Ubuntu system without Docker, the Docker file will be prescriptive.
