### ISSUE TITLE
Loading my data into HNN

### ISSUE THREAD

**Issue by ShiriMakov** [jonescompneurolab/hnn#251]
Hi!

I'm trying to load my own data (a .txt file). 
However, when going to File -> Load data file, I can't see my file.
I tried putting it in the same folder where the example data files are, and it doesn't show (even after restarting HNN).
I also tried putting it in a local folder on my computer, but I don't see how to reach it, probably because of the docker.

I'd be happy to hear your advice...

Thanks :)
Shiri

**Comment by blakecaldwell** [comment]
@ShiriMakov you are correct that files on your computer can be difficult to see within the container. There should be a `hnn_out` directory that was created in your home directory. This directory is special in the sense that it can be seen inside and outside the docker container. If you place your own data somewhere in `hnn_out`  are you able to find it from HNN?

**Comment by ShiriMakov** [comment]
Thanks, it worked :)
