### ISSUE TITLE
Problems loading data

### ISSUE THREAD

**Issue by ShiriMakov** [jonescompneurolab/hnn#253]
Hi!

I have encountered a problem loading a .txt file and was recommended by the GUI to report it.
I'm attaching the file I tried to load.
Waiting for your insights....

Thanks :)

Shiri

[ERP_for_hnn.txt](https://github.com/jonescompneurolab/hnn/files/5421488/ERP_for_hnn.txt)

**Comment by ShiriMakov** [comment]
I'm adding now that after several attempts to open the file, The whole hnn_out folder had disappeared.
I can't see why that happened...
Maybe you have an idea?
Also - how can I recover it?

Thanks....

**Comment by blakecaldwell** [comment]
This is really strange. I can load the data file in hnn. Just checking that you using File->Load data file? As far as the folder disappearing there is no code that should remove directories in HNN. I don't even think this would be possible with reinstalling. Can you describe what OS and installation method you used?

If you're still having the problem, we need the console output to see what exception was raised. This is displayed in a terminal window if you aren't using docker. If you are using docker, it's in the `hnn_docker.log` located in the main `hnn` directory. If you can attach that log to this issue, that would be very helpful.

**Comment by blakecaldwell** [comment]
@ShiriMakov any update?

**Comment by blakecaldwell** [comment]
Closing for now without more debugging info. Please feel free to reopen this issue if you are still experiencing issues.
