### ISSUE TITLE
KeyError: 'interval'

### ISSUE THREAD

**Issue by mkhalil8** [jonescompneurolab/hnn#254]
Hi all,

I get the following error whenever I run any simulation on HNN-NetPyne,

File "/anaconda3/lib/python3.6/site-packages/netpyne/cell/inputs.py", line 148, in createPoissonPattern
    T = params['interval'] #self.p_ext['t_interval'][1]
KeyError: 'interval'

My understanding is that the key "interval" is not present in the dictionary params, I have tried to look up the params file with no clue,

Any help with that?

**Comment by blakecaldwell** [comment]
Hi @mkhalil8 It looks like the key 'interval' is expected in netpyne code, but when I looked in the [current version](https://github.com/Neurosim-lab/netpyne/blob/development/netpyne/cell/inputs.py#L137-L162), the key 'internval' isn't used. Does the error persist if you upgrade your netpyne version? I see that there have been a lot of commits in netpyne over the past several months related to poisson inputs.

**Comment by mkhalil8** [comment]
Hi Blake, Nice to hear from you.

I updated Netpyne using Git repository and that did the trick, It is working now.

Thanks for your help :)

**Comment by blakecaldwell** [comment]
Good to hear!
