### ISSUE TITLE
Running GUI with Oscar Issue

### ISSUE THREAD

**Issue by lzimbalist** [jonescompneurolab/hnn#258]
I've been having some trouble getting the GUI up and running while trying to run HNN through Oscar. It seems that everything is working properly, but the GUI never appears. Is there any way to troubleshoot this?

**Comment by rythorpe** [comment]
Can you share the commands you entered to initialize the singularity container?

**Comment by lzimbalist** [comment]
After logging onto Oscar I ran:
```
interact -n 16
singularity pull docker://jonescompneurolab/hnn
singularity run hnn_latest.sif
```
I know the setup instructions say that the run command should be running hnn.simg but when I try that it gives me a "FATAL" message that it couldn't open the image. My directory has hnn_lastest.sif in it which is why I tried running that

**Comment by rythorpe** [comment]
Ahh yes, we need to update the instructions because there was a change in how Oscar implements singularity runscripts  (@blakecaldwell was this due to an update on Singularity's end, a problem with our runscript, or an issue with Oscar?). @lzimbalist now that you have `hnn_latest.sif` in your home directory, try
```
singularity shell hnn_latest.sif
source /home/hnn_user/hnn_envs
cd /home/hnn_user/hnn_source_code
python3 hnn.py
```

**Comment by lzimbalist** [comment]
I get 
```
qt.qpa.xcb: could not connect to display 172.20.200.74:24.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```
when running that

**Comment by lzimbalist** [comment]
Does this mean there's a problem with my XQuartz?

**Comment by rythorpe** [comment]
> Does this mean there's a problem with my XQuartz?

I'm assuming you initialized your ssh connect with x-forwarding enabled (i.e., `ssh -X usrname@ssh.brown.edu` for linux or `ssh -Y usrname@ssh.brown.edu` for Mac)?

**Comment by lzimbalist** [comment]
Oops! I was running with -X instead of -Y. Just confirming that in the future I need to run the shell to get the GUI working

**Comment by rythorpe** [comment]
> Oops! I was running with -X instead of -Y. Just confirming that in the future I need to run the shell to get the GUI working

Great! Yes, you will need to use a singularity shell to initialize HNN at least for the time being.

**Comment by lzimbalist** [comment]
Sorry one last question! If I want to transfer files between the two, is there anything special I need to do? I have tried just using scp but it doesn't seem to recognize a lot of the HNN folders and I think it's because of the need to open up a shell in order to get to HNN?

**Comment by rythorpe** [comment]
HNN always writes simulation param and data files to hnn_out in your home directory. You should be able to transfer files via scp by referencing files contained in `~/hnn_out/data` or `~/hnn_out/param`.

**Comment by lzimbalist** [comment]
Hi! I've been using HNN without trouble for the last couple of weeks (since you helped me get it set up – thanks!). It was working fine this morning, but when I tried to open it up just now I got this error message: 
```
qt.qpa.xcb: could not connect to display 172.20.4.217:19.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted
```
When I tried reinstalling (rerunning the `singularity docker pull` message, I got a "FATAL" error)
Have you seen this before? Any ideas on what could fix this?

**Comment by rythorpe** [comment]
> Hi! I've been using HNN without trouble for the last couple of weeks (since you helped me get it set up – thanks!). It was working fine this morning, but when I tried to open it up just now I got this error message:
> 
> ```
> qt.qpa.xcb: could not connect to display 172.20.4.217:19.0
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
> 
> Aborted
> ```
> 
> When I tried reinstalling (rerunning the `singularity docker pull` message, I got a "FATAL" error)
> Have you seen this before? Any ideas on what could fix this?

This looks like the same error you got [earlier](https://github.com/jonescompneurolab/hnn/issues/258#issuecomment-729910776) when x-forwarding wasn't enabled properly. Did anything change with your local x-client or how you initiated x-forwarding in your ssh session?

**Comment by lzimbalist** [comment]
I'm not sure what was happening but this morning it seemed to be working again, thanks!

**Comment by rythorpe** [comment]
Great! I'm going to go ahead and close this issue. Feel free to open again if the issue arises again @lzimbalist.
