### ISSUE TITLE
Unable to load Param File

### ISSUE THREAD

**Issue by NoPenguinsLand2** [jonescompneurolab/hnn#259]
Hello all,

I got an error where after running simulation, the GUI won't load the results. Also trying to load the same parameter file failed.

How I first encounter this issue: after successfully running simulation on old parameter file, I renamed and saved as a new parameter file, changed the inputs, and ran again. The simulation ran successfully but upon completion, I received this pop-up window, screenshot attached. The error message on the terminal is also attached. I received the same error message when I tried to load parameter file, and changing the parameter file name.

I also attached the parameter file here.

Any help would be greatly appreciated!

[CenterCondRightHemiMovie02Test02.param.zip](https://github.com/jonescompneurolab/hnn/files/5564073/CenterCondRightHemiMovie02Test02.param.zip)

![20201118_142846](https://user-images.githubusercontent.com/41695885/99615270-1a485980-29e9-11eb-86e7-3b784fb04f53.jpg)
![20201118_142936](https://user-images.githubusercontent.com/41695885/99615272-1caab380-29e9-11eb-9584-1db99fbdea7d.jpg)
![20201118_142944](https://user-images.githubusercontent.com/41695885/99615274-1e747700-29e9-11eb-911f-3a08d64b188d.jpg)

**Comment by blakecaldwell** [comment]
Hi, thanks for reporting this issue. The Traceback above was most helpful. The problem appears to be that 2 inputs are missing from their typical sequential ordering in the param file. Unfortunately, the code is missing some checks if the file is edited directly. Is that your use case here?

You can work around the error by adding these lines to the parameter file that will act as placeholders for the missing inputs. That should allow you to load the param file and run a simulation. Note that the parameters specify inputs with a start time after the simulation ends, have 0 spikes, and have synaptic weights of 0. Each of these settings makes the input non-effective to the simulation.

```
t_evprox_14: 5000
sigma_t_evprox_14: 10
numspikes_evprox_14: 0
gbar_evprox_14_L2Pyr_ampa: 0.0
gbar_evprox_14_L2Pyr_nmda: 0.0
gbar_evprox_14_L2Basket_ampa: 0.0
gbar_evprox_14_L2Basket_nmda: 0.0
gbar_evprox_14_L5Pyr_ampa: 0.0
gbar_evprox_14_L5Pyr_nmda: 0.0
gbar_evprox_14_L5Basket_ampa: 0.0
gbar_evprox_14_L5Basket_nmda: 0.0
t_evprox_23: 5000
sigma_t_evprox_23: 10
numspikes_evprox_23: 0
gbar_evprox_23_L2Pyr_ampa: 0.00
gbar_evprox_23_L2Pyr_nmda: 0.0
gbar_evprox_23_L2Basket_ampa: 0.0
gbar_evprox_23_L2Basket_nmda: 0.0
gbar_evprox_23_L5Pyr_ampa: 0.00
gbar_evprox_23_L5Pyr_nmda: 0.0
gbar_evprox_23_L5Basket_ampa: 0.0
gbar_evprox_23_L5Basket_nmda: 0.0
```

**Comment by NoPenguinsLand2** [comment]
That fixes the problem! Thank you very much!

**Comment by blakecaldwell** [comment]
@NoPenguinsLand2 Great! Can you confirm that you were changing the parameter file directly or did the GUI leave gaps in the ordering?

**Comment by NoPenguinsLand2** [comment]
Prior to encountering this issue, I never modified the parameter file directly. It was all done on GUI so I'm assuming GUI left gaps in the ordering.

**Comment by blakecaldwell** [comment]
Thanks, that's very helpful!
