### ISSUE TITLE
loading data

### ISSUE THREAD

**Issue by NoyHala** [jonescompneurolab/hnn#267]
Hi,
 When I try to load data to HNN I get the following exception:
 " WARNING: an exception occurred! Details can be found in 
    hnn_docker.log or the console output. "

I will appreciate your help
Thanks
Noy.

**Comment by blakecaldwell** [comment]
Hello, thanks for opening this issue. In order to understand what the problem could be, could you include the output from the command prompt when you get this error? Also, please specify what data file you are trying to load. Thanks.

**Comment by NoyHala** [comment]
Thank you for youre answer.
Attaches the file and the command prompt:
![comand prompt exception](https://user-images.githubusercontent.com/75626522/101454703-12217100-393a-11eb-9889-f431815f0b7b.PNG)
[ERF_ign_lh_Rh_EarlyAC_MNE_to_HNN.txt](https://github.com/jonescompneurolab/hnn/files/5657627/ERF_ign_lh_Rh_EarlyAC_MNE_to_HNN.txt)

I tried to save the  file in hnn_out folder and also in hnn_source_code/data folder.

thanks,
Noy

**Comment by blakecaldwell** [comment]
Thanks for uploading the screenshot and file. That helps. The permission denied error relates to WSL not being able to read the file you saved. I'm aware that there are some complications with moving files between Windows and WSL. I don't know if you did the copy via file explorer, but that can cause problems. Instead, you want to copy the file from within WSL/Ubuntu.

From the WSL prompt, the command will be something like:
```
cp /mnt/c/Users/PATH_TO_DATA_FILE.txt /home/noy_hala/hnn_source_code/data/
```

You can verify that reading the file works from WSL/Ubuntu (independent of HNN). This should show the first few lines of the file. If there's an error, HNN won't be able to read the file.
```
head /home/noy_hala/hnn_source_code/data/ERF_ign_lh_Rh_EarlyAC_MNE_to_HNN.txt
```

Hopefully that helps. Let us know how it goes.

Best,
Blake

**Comment by NoyHala** [comment]
It worked. thank you
