### ISSUE TITLE
failed to start application

### ISSUE THREAD

**Issue by hisacof** [jonescompneurolab/hnn#269]
Hello, I was able to install and start the HNN application but now I am receiving an error below . I reinstalled HNN but I am still getting the same message. Please advise how to fix this? Thank you, Hisako

hisako@EW19-00993:~/hnn_source_code$ python3 hnn.py
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

**Comment by hisacof** [comment]
Never mind. reinstalling the whole application including VcXsrv fixed. Thanks.

**Comment by blakecaldwell** [comment]
Good to hear. Thanks for posting the resolution.
