### ISSUE TITLE
Running HNN with Docker - Without SSH - Suggested Instructions or clarifications for Ubuntu 18.04 terminal

### ISSUE THREAD

**Issue by jling-NM** [jonescompneurolab/hnn#271]
Instructions at this location https://jonescompneurolab.github.io/hnn/installer/docker/ did not work for me.

> docker run -d -v "$HOME/hnn_out":"$HOME/hnn_out" --env XAUTHORITY=/tmp/.Xauthority --env SYSTEM_USER_DIR="$HOME" --name hnn_container jonescompneurolab/hnn`

> export USE_SSH=0
> docker exec --env SYSTEM_USER_DIR="$HOME" --env DISPLAY=":0" -u "$(id -u)" hnn_container /home/hnn_user/start_hnn.sh

Results in this error:
HNN failed to start GUI using DISPLAY=:0
/home/hnn_user/start_hnn.sh: line 59:    22 Aborted                 (core dumped) python3 hnn.py

Using suggested **xhost +local:docker** does not work.

However, these steps correctly launch the gui in a local terminal:
```
> mkdir -p $HOME/hnn_out

> docker run -d \
--name hnn_container \
--env SYSTEM_USER_DIR="$HOME" \
-v "$HOME/hnn_out":"$HOME/hnn_out" \
-v /tmp/.X11-unix:/tmp/.X11-unix \
--env XAUTHORITY=/tmp/.Xauthority \
jonescompneurolab/hnn

> docker exec \
--env DISPLAY=":0" \
--env SYSTEM_USER_DIR="$HOME" \
--env MPLCONFIGDIR="$HOME/hnn_out" \
--user `id -u`:`id -g` \
hnn_container /home/hnn_user/start_hnn.sh


```
This can all be done in a single step:
```
> docker run -it --rm \
--user `id -u`:`id -g` \
--env SYSTEM_USER_DIR="$HOME" \
--env XAUTHORITY=/tmp/.Xauthority \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-v "$HOME/hnn_out":"$HOME/hnn_out" \
jonescompneurolab/hnn /home/hnn_user/start_hnn.sh
```

**Comment by jasmainak** [comment]
can you give this a try: https://jonescompneurolab.github.io/hnn-core/

and see if it satisfies your requirements? If not perhaps @blakecaldwell can help you diagnose the issue

**Comment by jling-NM** [comment]
We would like to pursue the HNN GUI version if possible as that is where are current experience is.
thanks

**Comment by blakecaldwell** [comment]
Closing because docker install is no longer recommended. Please see the current instructions for installing HNN without docker.
