### ISSUE TITLE
Running HNN with Docker - Using SSH - X11 forwarding instructions did not work in Ubuntu 18.04 terminal

### ISSUE THREAD

**Issue by jling-NM** [jonescompneurolab/hnn#272]
The instructions for SSH in linux do not appear to work or are incomplete.

https://jonescompneurolab.github.io/hnn/installer/docker/
```

docker run -d -v "$HOME/hnn_out":"$HOME/hnn_out" --env XAUTHORITY=/tmp/.Xauthority --env SYSTEM_USER_DIR="$HOME" --name hnn_container jonescompneurolab/hnn

export USE_SSH=1
SSH_PRIVKEY="installer/docker/id_rsa_hnn"
ssh-keygen -f "$SSH_PRIVKEY" -t rsa -N ''

export DISPLAY=127.0.0.1:0
export XAUTHORITY=/tmp/.Xauthority
export SYSTEM_USER_DIR="$HOME"
ssh -o SendEnv=DISPLAY -o SendEnv=XAUTHORITY -o SendEnv=SYSTEM_USER_DIR -o SendEnv=TRAVIS_TESTING -o PasswordAuthentication=no -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -v -i "SSH_PRIVKEY" -R 6000:127.0.0.1:6000 hnn_user@localhost -p 32791
```

Results in the following error:
Warning: Identity file SSH_PRIVKEY not accessible: No such file or directory.
OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to localhost [127.0.0.1] port 32791.
debug1: connect to address 127.0.0.1 port 32791: Connection refused
ssh: connect to host localhost port 32791: Connection refused

 Perhaps -i "SSH_PRIVKEY" should be  -i "$SSH_PRIVKEY"?
I'm not sure how to resolve the port error.

These instruction say "Commands should be run from the HNN source code directory". Should i then build the Docker container from this source code so it includes the key file?
Some clarification would be greatly appreciated.

**Comment by blakecaldwell** [comment]
Closing because docker install is no longer recommended. Please see current instructions for installing HNN without docker.
