### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by hisacof** [jonescompneurolab/hnn#273]
Hello,

I was going through tutorial and running the simulation of ERP. I quit the simulation while the trials were still counting accidentally. I wanted to rerun the simulation but I am receiving the error below. I close the all the way and also Ubuntu and restarted but I stil getting the same error. Please advise how this can be fixed. Thank you for your help. 

WARNING: an exception occurred! Details can be found in hnn_docker.log or the console output. We would greatly appreciate reporting this issue to our development team: https://github.com/jonescompneurolab/hnn/issues

**Comment by hisacof** [comment]
the output in terminal shown below.  I am now sure why hnn started looking into the out out folder instead of source code folder.

:~/hnn_source_code$ python3 hnn.py
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-hisako'
Warning: could not read file: /home/hisako/hnn_out/data/ERPYes100Trials/dpl.txt
Warning: could not read file: /home/hisako/hnn_out/data/ERPYes100Trials/spk.txt
Traceback (most recent call last):
  File "hnn.py", line 37, in <module>
    runqt5()
  File "hnn.py", line 27, in runqt5
    sys.exit(app.exec_())
  File "/home/hisako/hnn_source_code/hnn_qt5.py", line 3443, in selParamFileDialog
    self.initSimCanvas() # recreate canvas
  File "/home/hisako/hnn_source_code/hnn_qt5.py", line 4100, in initSimCanvas
    self.m = SIMCanvas(paramf, parent = self, width=10, height=1, dpi=getmplDPI(), optMode=optMode) # also loads data
  File "/home/hisako/hnn_source_code/simdat.py", line 276, in __init__
    self.plot()
  File "/home/hisako/hnn_source_code/simdat.py", line 756, in plot
    self.plotsimdat()  # creates self.axdipole
  File "/home/hisako/hnn_source_code/simdat.py", line 620, in plotsimdat
    xo = self.plotinputhist(xl, dinty)
  File "/home/hisako/hnn_source_code/simdat.py", line 297, in plotinputhist
    extinputs = spikefn.ExtInputs(dfile['spk'], dfile['outparam'])
  File "/home/hisako/hnn_source_code/spikefn.py", line 80, in __init__
    self.inputs = self.__get_extinput_times(fspk)
  File "/home/hisako/hnn_source_code/spikefn.py", line 156, in __get_extinput_times
    s_all = np.loadtxt(open(fspk, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hisako/hnn_out/data/ERPYes100Trials/spk.txt'

**Comment by rythorpe** [comment]
@hisacof are you still having trouble running the ERP simulation? If so, try deleting your `/home/hisako/hnn_out/data/ERPYes100Trials` directory and re-running the simulation. I think HNN it trying to find a non-existent file that it thinks exists.

**Comment by hisacof** [comment]
I should have updated earlier here. Sorry about that. Yes, I did figure this out. I forgot to change the parameter name before running a simulation so I thought I should delete them (including 'default'). Thank you!
