### ISSUE TITLE
[Feature Request] Configurable output directory

### ISSUE THREAD

**Issue by bloyl** [jonescompneurolab/hnn#28]
It would be useful if location of simulation output directory was configurable.
At the moment all output is saved in `~/hnn/...` it would be great if this could be set in hnn.cfg file.

This locations is set in 2 places and I'm unsure if one place overrides the other etc.

https://github.com/jonescompneurolab/hnn/blob/de20760842665440f02efc8c073e6693ef89b5d8/fileio.py#L136-L137

and

https://github.com/jonescompneurolab/hnn/blob/de20760842665440f02efc8c073e6693ef89b5d8/conf.py#L150-L152

**Comment by samnemo** [comment]
I pushed a fix to the development branch that looks for the dbase (base output directory) option in [paths] section of hnn.cfg . By default dbase isn't in hnn.cfg but you can add it to customize output. Try it out and let me know if it works for you. If so, I'll push it to the main branch.

**Comment by bloyl** [comment]
Thanks. I'll hopefully take a look over the weekend.

**Comment by bloyl** [comment]
Hi Sam,

I was just able test it. It seems to be working. there does seem to be an extra print that isn't needed. 
Line 219 of run.py.

Its up to you if you want to push it to master. Seems pretty minor for a release, I'm fine rebasing my working branch off of the development branch. 

Thanks for the fix.

**Comment by samnemo** [comment]
pushed feature to main branch along with other fix to param file; closing request
