### ISSUE TITLE
Tonic input throws error

### ISSUE THREAD

**Issue by lzimbalist** [jonescompneurolab/hnn#309]
I recently installed the GUI locally on my mac, but whenever I try to run a simulation that uses tonic inputs I get this error message: 

```
Traceback (most recent call last):
  File "/Users/lilazimbalist/Desktop/hnn/hnn/qt_thread.py", line 237, in run
    self._run(banner=banner, sim_length=sim_length)  # run simulation
  File "/Users/lilazimbalist/Desktop/hnn/hnn/qt_thread.py", line 272, in _run
    sim_data = simulate(net)
  File "/Users/lilazimbalist/Desktop/hnn/hnn/qt_thread.py", line 99, in simulate
    numspikes_params = net.params['numspikes_*']
  File "/Users/lilazimbalist/miniconda3/envs/hnn/lib/python3.7/site-packages/hnn_core/params.py", line 318, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'numspikes_*'
```
After throwing this error, everything seems to freeze, and I am unable to work with the GUI again unless I SIGQUIT out and reopen it. 

Has anyone seen this error before? Any help with this would be greatly appreciated!

**Comment by jasmainak** [comment]
I think the issue is your param file does not contain parameters starting with `numspikes_` and there is no check for this

any volunteers to fix? @kenloi @rythorpe @ntolley ?

**Comment by ntolley** [comment]
@lzimbalist I am unable to reproduce this locally (however I am not using a Mac). Can you email your param file if you're still planning to work with the GUI?

For reference I am just starting with the `default.param` file and adding a tonic input from the interface.

**Comment by lzimbalist** [comment]
I actually think it's happening because I downloaded the wrong backend code (I think I'm trying to run it on hnn core code instead of the gui one). Thanks for your help though!
