### ISSUE TITLE
Failed running sim using default.param (Mac)

### ISSUE THREAD

**Issue by LizzieYK** [jonescompneurolab/hnn#319]
Hello all,

I just installed the HNN on my Mac (macOS Big Sur 11.4), but I am having trouble running simulation with an error message in a pop-up window, saying "Failed running sim using /Users/elizabeth/hnn_out/param/default.param. Saved data/figures in: /Users/elizabeth/hnn_out/data/default". Meanwhile, the terminal outputs are as follows, and the process never terminates.

<img width="776" alt="Screenshot 2022-03-09 at 13 12 09" src="https://user-images.githubusercontent.com/101181867/157448382-c2ebe097-fe98-41ca-b9d5-4982afbd3d48.png">

Many thanks in advance for your help!

Best,
Lizzie

PS: results of the post-install check is attached as well. Hope it helps.
<img width="771" alt="Screenshot 2022-03-09 at 13 07 18" src="https://user-images.githubusercontent.com/101181867/157447875-27046761-3bc4-4ffb-8282-23ffbe800cdb.png">

**Comment by rythorpe** [comment]
Hi @LizzieYK, I suspect that something in your `/Users/elizabeth/hnn_out/data/default/` directory is corrupted. Try deleting this directory (run `$ rm -rf /Users/elizabeth/hnn_out/data/default` in your terminal) and re-running the simulation.

**Comment by LizzieYK** [comment]
Hi @rythorpe, it worked! Thank you so much for the advice!
