### ISSUE TITLE
Error executing Set Parameters from File

### ISSUE THREAD

**Issue by ewofix** [jonescompneurolab/hnn#342]
When I press "Set parameters from file" following Figure 4B in the paper "Human Neocortical Neurosolver (HNN), a new software tool for interpreting the cellular and network origin of human MEG/EEG data," and open the ERPYes100Trials.param file, I encounter the error message: "WARNING: an exception occurred! Details can be found in the console output. Please include this output when opening an issue on GitHub: https://github.com/jonescompneurolab/hnn/issues." As a result, HNN is not functioning. What could be the reason for this issue?

**Comment by rythorpe** [comment]
Can you paste the console output here? Or was there not anything else?

I suspect your issue has to do with corrupted files in your `hnn_out/data/` directory. Try deleting your `hnn_out/data/ERPYes100Trials` folder, and try again.

**Comment by ewofix** [comment]
After deleting hnn_out/data/ERPYes100Trials and rerunning hnn, I encountered errors like "WARNING: no dipole data at /home/myeongju/hnn_out/data/ERPYes100Trials/dpl.txt" when trying to execute tools within the View such as "View Simulation Dipoles" or "View Simulation Spiking Activity". It seems that crucial data has been inadvertently deleted. Should I be worried that important files were also deleted? How can I fix this issue?

![스크린샷(3994)](https://github.com/jonescompneurolab/hnn/assets/91768616/d570fd5e-288b-427a-ab68-406bde721dd1)

**Comment by ewofix** [comment]
![스크린샷(3996)](https://github.com/jonescompneurolab/hnn/assets/91768616/d55c75ed-7366-4314-ada2-1ed6d8027eda)
It seems like the simulation failed while attempting to run. If that's correct, could you let me know how to delete the saved files if needed?

**Comment by rythorpe** [comment]
After you delete the `hnn_out/data/ERPYes100Trials` folder, you'll need to re-run the simulation before you can plot the dipole or spiking activity. Did you try this already?

**Comment by ewofix** [comment]
I reinstalled Ubuntu and tried running it again, and the issue was resolved. Thank you for your help!
