### ISSUE TITLE
qt issue hnn_core, also gui issue missing tabs

### ISSUE THREAD

**Issue by mschendel** [jonescompneurolab/hnn#344]
Hello,
I tried using pip install hnn_core and pip install hnn_core[gui]

No errors when I do python -c 'import hnn_core'
But when I try tutorial 01, I get a qt errror at  net.plot_cells()

> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
> 
> Aborted

Here is my environment qt info:

> (hnn) mschendel@thor:~$ conda list | grep qt
> mne-qt-browser            0.6.1              pyha770c72_0    conda-forge
> pyqt                      5.15.9          py311hf0fb5b6_5    conda-forge
> pyqt5                     5.15.10                  pypi_0    pypi
> pyqt5-plugins             5.15.9.2.3               pypi_0    pypi
> pyqt5-qt5                 5.15.2                   pypi_0    pypi
> pyqt5-sip                 12.13.0                  pypi_0    pypi
> pyqt5-tools               5.15.9.3.3               pypi_0    pypi
> pyqtgraph                 0.13.3             pyhd8ed1ab_0    conda-forge
> pyvistaqt                 0.11.0             pyhd8ed1ab_1    conda-forge
> qt-main                   5.15.8              h82b777d_17    conda-forge
> qt5-applications          5.15.2.2.3               pypi_0    pypi
> qt5-tools                 5.15.2.1.3               pypi_0    pypi
> qtconsole                 5.5.1              pyhd8ed1ab_0    conda-forge
> qtconsole-base            5.5.1              pyha770c72_0    conda-forge
> qtpy                      2.4.1              pyhd8ed1ab_0    conda-forge
> vtk                       9.2.6           qt_py311h1234567_220    conda-forge
> vtk-base                  9.2.6           qt_py311h1234567_220    conda-forge
> vtk-io-ffmpeg             9.2.6           qt_py311h1234567_220    conda-forge

I am using Ubuntu 22.04.4 LTS

I try to load the hnn-gui, but see attached - I don't see the tabs row for File, Edit (etc) or for Set Parameters (etc).  I only see Simulation, Network connectivity.  I am not sure if this is an issue with the old version of Firefox my admin is running, or something else.
![hnn_widget_full](https://github.com/jonescompneurolab/hnn/assets/18619031/a048f8eb-544c-4a19-b971-ee08cfcb5276)

Thanks for any help, 
Megan

**Comment by ntolley** [comment]
Thanks for bringing this to our attention @mschendel!

I've moved this issue over to the hnn-core github page and will respond there
