### ISSUE TITLE
View / View simulation dipoles problem

### ISSUE THREAD

**Issue by neuroman314** [jonescompneurolab/hnn#5]
Under Mint18.3:
View / View simulation dipoles
elicits
File "visdipole.py", line 2, in <module>
    from PyQt5.QtWidgets import QMainWindow, QAction, qApp, QApplication, QToolTip, QPushButton, QFormLayout
ImportError: No module named PyQt5.QtWidgets

But python3-pyqt5 has been installed, and
ted@fleck ~/Desktop $ python3 -c "from PyQt5 import QtWidgets"
generates no complaints.

**Comment by samnemo** [comment]
Was calling wrong Python version from HNN; fixed
