### ISSUE TITLE
[Feature Request]: Load data of a variable sampling rate

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn#7]
It'd be great to be able to load a data file without having to change the sampling rate of the time series, or at least have a standard set of sampling rates to choose from so that more datasets are compatible while minimizing information loss.

**Comment by blakecaldwell** [comment]
Experimental data of any sampling rate can be loaded. HNN will infer the sampling rate from the spacing of times given in the first column of the data file. Spectrograms/RMSE will use this sampling rate. Please reopen if issues persist upon further testing.

Thanks for bringing this up. Previous versions (before spring 2019) would have incorrectly calculated RMSE.
