### ISSUE TITLE
View Simulation Spiking Activity Input Histogram Discrepancy

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn#8]
The time histograms generated in the upper plot of View>View Simulation Spiking Activity shows inputs that shouldn't exist given the simulation parameters.

![spiking_activity](https://user-images.githubusercontent.com/20212206/43733532-01ad0428-9983-11e8-87ec-f137e217d62c.png)
![main_window](https://user-images.githubusercontent.com/20212206/43734367-7ba878f0-9985-11e8-96ae-57eef4d2aa55.png)
[N20_Pc-Fz_03_prox_only.param.txt](https://github.com/jonescompneurolab/hnn/files/2263610/N20_Pc-Fz_03_prox_only.param.txt)

**Comment by samnemo** [comment]
Thanks - can you provide the .param file as well so we can debug? (not the .param.txt file)

**Comment by rythorpe** [comment]
It won't let me upload a .param file type. Would a zip file work?

**Comment by samnemo** [comment]
Yeah, a zip file including the .param file would be helpful.

**Comment by rythorpe** [comment]
[N20_Pc-Fz_03_prox_only.param.zip](https://github.com/jonescompneurolab/hnn/files/2263700/N20_Pc-Fz_03_prox_only.param.zip)

**Comment by samnemo** [comment]
Fixed this issue in release 0.0.4: Make sure raster visualization properly checks for presence of rhythmic vs evoked inputs when deciding what to draw on synaptic input histogram.
