### ISSUE TITLE
unable to start gui hnn in kali linux

### ISSUE THREAD

**Issue by INNFINITEMINDS** [jonescompneurolab/hnn#83]
docker-compose run hnn
ERR: could not create /home//hnn_user/hnn_out/data
Trying to start HNN with DISPLAY=192.168.99.1:0
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=192.168.99.1:0
Trying to start HNN with DISPLAY=192.168.65.2:0
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=192.168.65.2:0
Trying to start HNN with DISPLAY=0:
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=0:
Trying to start HNN with DISPLAY=192.168.99.1:1
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=192.168.99.1:1
Trying to start HNN with DISPLAY=192.168.65.2:1
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=192.168.65.2:1
Trying to start HNN with DISPLAY=1:
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=1:
Trying to start HNN with DISPLAY=192.168.99.1:2
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=192.168.99.1:2
Trying to start HNN with DISPLAY=192.168.65.2:2
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=192.168.65.2:2
Trying to start HNN with DISPLAY=2:
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=2:
Trying to start HNN with DISPLAY=192.168.99.1:3
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=192.168.99.1:3
Trying to start HNN with DISPLAY=192.168.65.2:3
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=192.168.65.2:3
Trying to start HNN with DISPLAY=3:
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=3:
Trying to start HNN with DISPLAY=192.168.99.1:4
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=192.168.99.1:4
Trying to start HNN with DISPLAY=192.168.65.2:4
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=192.168.65.2:4
Trying to start HNN with DISPLAY=4:
ERR: could not create /home//hnn_user/hnn_out/data
HNN failed to start GUI using DISPLAY=4:
Failed to start HNN on any X port at host

**Comment by blakecaldwell** [comment]
This is fixed by #84 and a new docker container is available to be downloaded `docker-compose pull`.

Also, I've added more to the docker troubleshooting guide:
https://jonescompneurolab.github.io/hnn/installer/docker/troubleshooting.html
